define(`C_maj',  `[C,E,G,]$1')dnl
define(`Db_maj', `[_D,F,_A,]$1')dnl
define(`D_maj',  `[D,^F,A,]$1')dnl
define(`Eb_maj', `[_E,G,_B,]$1')dnl
define(`E_maj',  `[E,^G,B,]$1')dnl
define(`F_maj',  `[F,A,C]$1')dnl
define(`Gb_maj', `[_G,_B,_D]$1')dnl
define(`G_maj',  `[G,B,D]$1')dnl
define(`Ab_maj', `[_A,C_E]$1')dnl
define(`A_maj',  `[A,^CE]$1')dnl
define(`Bb_maj', `[_B,DF]$1')dnl
define(`B_maj',  `[B,^D^F]$1')dnl
dnl
define(`C_min',  `[C,_E,G,]$1')dnl
define(`Db_min', `[_D,_F,_A,]$1')dnl
define(`D_min',  `[D,F,A,]$1')dnl
define(`Eb_min', `[_E,_G,_B,]$1')dnl
define(`E_min',  `[E,G,B,]$1')dnl
define(`F_min',  `[F,_A,C]$1')dnl
define(`Gb_min', `[_G,__B,_D]$1')dnl
define(`G_min',  `[G,_B,D]$1')dnl
define(`Ab_min', `[_A,_C_E]$1')dnl
define(`A_min',  `[A,CE]$1')dnl
define(`Bb_min', `[_B,_DF]$1')dnl
define(`B_min',  `[B,D^F]$1')dnl
dnl
define(`C_7',    `[C,E,G,B,]$1')dnl
define(`Db_7',   `[_D,F,_A,C]$1')dnl
define(`D_7',    `[D,^F,A,^C]$1')dnl
define(`Eb_7',   `[_E,G,_B,D]$1')dnl
define(`E_7',    `[E,^G,B,^D]$1')dnl
define(`F_7',    `[F,A,CE]$1')dnl
define(`Gb_7',   `[_G,_B,_DF]$1')dnl
define(`G_7',    `[G,B,D^F]$1')dnl
define(`Ab_7',   `[_A,C_EG]$1')dnl
define(`A_7',    `[A,^CE^G]$1')dnl
define(`Bb_7',   `[_B,DFA]$1')dnl
define(`B_7',    `[B,^D^F^A]$1')dnl
