cc_library(
  name = "bigint",
  srcs = ["bigint.cc"],
  hdrs = ["bigint.h"],
)

cc_binary(
  name = "p065",
  srcs = ["p065.cc"],
  deps = [":bigint"],
)

cc_binary(
  name = "p089",
  srcs = ["p089.cc"],
)

cc_binary(
  name = "p092",
  srcs = ["p092.cc"],
)
