[package]
name = "euler81"
version = "0.1.0"
authors = ["Paul Bartlett <pdbartlett@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
