# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'https://rubygems.org'

gem "middleman", "~>3.1.2"

gem "middleman-minify-html"
gem "middleman-deploy"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"
