java_binary(
  name = "assignment0",
  srcs = ["helloworld.java"],
  main_class = "HelloWorld",
)

java_binary(
  name = "assignment1",
  srcs = [
    "Percolation.java",
    "PercolationStats.java",
  ],
  deps = ["@algs4_jar//jar"],
  main_class = "Percolation",
)
